blueprint:
  name: Room Occupancy with Motion, Espresense, Custom Timers, and Input Boolean - 1.3.0
  description: |
    Detect room occupancy using a motion sensor or occupancy sensor as the primary detector and Espresense as a secondary sensor. 
    After motion stops, the automation relies on Espresense to determine if the room is still occupied. 
    If neither motion nor Espresense detect occupancy, the room will be marked as unoccupied after a timeout. 
    You can select your motion sensor or occupancy sensor, Espresense sensor, input_boolean for occupancy status, and custom timer entity.
    
  # Version Control
  # Version 1.0.0 - Initial creation of the blueprint, supports motion, Espresense, timer, and input_boolean for occupancy.
  # Version 1.1.0 - Added ability to choose timer entity.
  # Version 1.2.0 - Added support for customizable input_boolean to track room occupancy.
  # Version 1.2.1 - Minor cleanup and comments for better readability.
  # Version 1.3.0 - Allowed motion sensor input to also accept occupancy sensors.

  domain: automation
  input:
    motion_sensor:
      name: Motion or Occupancy Sensor
      description: Select the motion or occupancy sensor to use for detecting movement or occupancy.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          
    espresense_sensor:
      name: Espresense Sensor
      description: Select the Espresense sensor to use for detecting presence.
      selector:
        entity:
          domain: binary_sensor
          device_class: presence
          
    motion_timeout:
      name: Motion Timeout
      description: How long to wait after motion stops before checking Espresense.
      default: 60
      selector:
        number:
          min: 10
          max: 600
          unit_of_measurement: seconds
          mode: slider

    motion_timer:
      name: Motion Timeout Timer
      description: Select the timer entity to use for motion timeout.
      selector:
        entity:
          domain: timer

    room_occupied_boolean:
      name: Room Occupied Input Boolean
      description: Select the input_boolean entity that represents room occupancy.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'

action:
  # When motion or occupancy is detected, mark the room as occupied and start the motion timer
  - service: input_boolean.turn_on
    target:
      entity_id: !input room_occupied_boolean
  - service: timer.start
    target:
      entity_id: !input motion_timer
    data:
      duration: "{{ input.motion_timeout }}"

# When motion or occupancy stops, start the countdown timer to check Espresense
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    
action:
  - service: timer.start
    target:
      entity_id: !input motion_timer
    data:
      duration: "{{ input.motion_timeout }}"

# After the motion timeout finishes, check Espresense to see if the room is still occupied
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input motion_timer
      
condition: []
action:
  - choose:
      # If Espresense detects presence, keep the room marked as occupied
      - conditions:
          - condition: state
            entity_id: !input espresense_sensor
            state: 'on'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input room_occupied_boolean
    default:
      # If no presence is detected, mark the room as unoccupied
      - service: input_boolean.turn_off
        target:
          entity_id: !input room_occupied_boolean
